names:
- backpack
- cup
- bowl
- banana
- apple
- orange
- chair
- couch
- potted plant
- bed
- dining table
- laptop
- mouse
- keyboard
- cell phone
- book
- clock
- vase
- scissors
- hair drier
- toothbrush
nc: 21
train: ../data/yolo_dataset/smoke_test/images
val: ../data/yolo_dataset/smoke_test/images
